# Generated by Django 3.0.4 on 2020-04-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('shor_name', models.CharField(max_length=30, unique=True, verbose_name='Nombre Corto')),
                ('estado', models.BooleanField(default=False, verbose_name='Anulado')),
            ],
        ),
    ]
