# Generated by Django 3.0.4 on 2020-04-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20200422_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='habilidades',
        ),
    ]
