# Generated by Django 3.0.4 on 2020-04-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_compared'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compared',
            options={'verbose_name': 'Mis Comparendos '},
        ),
    ]
