# Generated by Django 3.0.4 on 2020-04-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_auto_20200422_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compared',
        ),
        migrations.AddField(
            model_name='empleado',
            name='habilidad',
            field=models.ManyToManyField(to='persona.Habilidades'),
        ),
    ]
