# Generated by Django 3.0.4 on 2020-04-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_auto_20200422_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='habilidad',
        ),
        migrations.AddField(
            model_name='empleado',
            name='habili',
            field=models.ManyToManyField(to='persona.Habilidades'),
        ),
        migrations.AlterField(
            model_name='habilidades',
            name='habilidad',
            field=models.CharField(max_length=50, verbose_name='Habilidades'),
        ),
    ]
