# Generated by Django 3.0.4 on 2020-04-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0011_auto_20200422_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='habili',
            new_name='habilidades',
        ),
        migrations.RenameField(
            model_name='habilidades',
            old_name='habilidad',
            new_name='habilid',
        ),
    ]
