# Generated by Django 3.0.4 on 2020-05-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0013_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fullname',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombres Completos'),
        ),
    ]
