# Generated by Django 3.0.4 on 2020-05-31 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0014_empleado_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
