# Generated by Django 3.0.4 on 2020-06-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0015_auto_20200531_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
    ]
