# Generated by Django 3.0.4 on 2020-06-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0016_empleado_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidades',
            old_name='habilid',
            new_name='habilidad',
        ),
    ]
